export const companySubList = [
  {
    	image: 'https://seeu-applets.seeu-edu.com/images/static/google.jpg',
    	title: 'W同学',
    	subtitle: 'Software Engineer',
    	tag: '全职',
    	views: 2344,
    	file: '/backend/pdfs/google.pdf',
      },
      {
    	image: 'https://seeu-applets.seeu-edu.com/images/static/google.jpg',
    	title: 'L同学',
    	subtitle: 'Senior Data Scientist',
    	tag: '实习',
    	views: 3452,
    	file: '/backend/pdfs/google.pdf',
      },
      {
    	image: 'https://seeu-applets.seeu-edu.com/images/static/google.jpg',
    	title: 'X同学',
    	subtitle: 'Software Engineer',
    	tag: '实习',
    	views: 4697,
    	file: '/backend/pdfs/google.pdf',
      },
      {
      	image: 'https://seeu-applets.seeu-edu.com/images/static/google.jpg',
      	title: 'T同学',
      	subtitle: 'Software Engineer',
      	tag: '实习',
      	views: 4697,
      	file: '/backend/pdfs/meta.pdf',
      },
      {
      	image: 'https://seeu-applets.seeu-edu.com/images/static/google.jpg',
      	title: 'M同学',
      	subtitle: 'Software Engineer',
      	tag: '实习',
      	views: 4697,
      	file: '/backend/pdfs/meta.pdf',
      },
      {
      	image: 'https://seeu-applets.seeu-edu.com/images/static/google.jpg',
      	title: 'C同学',
      	subtitle: 'Software Engineer',
      	tag: '实习',
      	views: 4697,
      	file: '/backend/pdfs/meta.pdf',
      },
      {
      	image: 'https://seeu-applets.seeu-edu.com/images/static/google.jpg',
      	title: 'D同学',
      	subtitle: 'Software Engineer',
      	tag: '实习',
      	views: 4697,
      	file: '/backend/pdfs/meta.pdf',
      },
      {
      	image: 'https://seeu-applets.seeu-edu.com/images/static/google.jpg',
      	title: 'A同学',
      	subtitle: 'Software Engineer',
      	tag: '全职',
      	views: 2344,
    	file: '/backend/pdfs/google.pdf',
      },
      // Add more items as needed
  ];

export const universitySubList = [
  {
  	image: 'https://seeu-applets.seeu-edu.com/images/static/google.jpg',
  	title: 'W同学',
  	//subtitle: 'Software Engineer',
  	tag: '全职',
  	views: 2344,
  	file: '/backend/pdfs/google.pdf',
    },
    {
  	image: 'https://seeu-applets.seeu-edu.com/images/static/google.jpg',
  	title: 'L同学',
  	//subtitle: 'Senior Data Scientist',
  	tag: '实习',
  	views: 3452,
  	file: '/backend/pdfs/google.pdf',
    },
    {
  	image: 'https://seeu-applets.seeu-edu.com/images/static/google.jpg',
  	title: 'X同学',
  	//subtitle: 'Software Engineer',
  	tag: '实习',
  	views: 4697,
  	file: '/backend/pdfs/google.pdf',
    },
    {
    	image: 'https://seeu-applets.seeu-edu.com/images/static/google.jpg',
    	title: 'T同学',
    	//subtitle: 'Software Engineer',
    	tag: '实习',
    	views: 4697,
    	file: '/backend/pdfs/meta.pdf',
    },
    {
    	image: 'https://seeu-applets.seeu-edu.com/images/static/google.jpg',
    	title: 'M同学',
    	//subtitle: 'Software Engineer',
    	tag: '实习',
    	views: 4697,
    	file: '/backend/pdfs/meta.pdf',
    },
    {
    	image: 'https://seeu-applets.seeu-edu.com/images/static/google.jpg',
    	title: 'C同学',
    	//subtitle: 'Software Engineer',
    	tag: '实习',
    	views: 4697,
    	file: '/backend/pdfs/meta.pdf',
    },
    {
    	image: 'https://seeu-applets.seeu-edu.com/images/static/google.jpg',
    	title: 'D同学',
    	//subtitle: 'Software Engineer',
    	tag: '实习',
    	views: 4697,
    	file: '/backend/pdfs/meta.pdf',
    },
    {
    	image: 'https://seeu-applets.seeu-edu.com/images/static/google.jpg',
    	title: 'A同学',
    	//subtitle: 'Software Engineer',
    	tag: '全职',
    	views: 2344,
  	    file: '/backend/pdfs/google.pdf',
    },
    // Add more items as needed
];
